### ISSUE TITLE
Feature Request: allow for custom propagation time

### ISSUE THREAD

**Issue by antedebaas** [kaechele/certbot-dns-pdns#35]
Hi,
could you add the possibility to customize the propagation time.
e.g. with a commandline switch --dns-pnds-propagation-seconds=20 for example?

**Comment by kaechele** [comment]
Hey there. Sorry for the delay. I will look into this shortly.

**Comment by antedebaas** [comment]
No problem. Take your time!

**Comment by kaechele** [comment]
OK, so I just checked.
The plugin actually already has the commandline parameter `--dns-pdns-propagation-seconds`.
I just tried it and it works, can you check on your end as well?

**Comment by antedebaas** [comment]
oh great.
i just checked and it indeed seems to work.
